package entry;

import java.util.ArrayList;
import java.util.List;

public class Subject {

    private String name;
    private int subjectCode;
    private List<String> prerequisites;
    private List<Subject> prerequisitesConnections;

    public Subject() {
        this.prerequisites = new ArrayList<>();
        this.prerequisitesConnections = new ArrayList<>();
    }

    /*
    Name of the subject
     */
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /*
    Gives the name of all the prerequisites
     */
    public List<String> getPrerequisites() {
        return prerequisites;
    }

    public void setPrerequisites(List<String> prerequisites) {
        this.prerequisites = prerequisites;
    }

    /*
       List of all prerequisite Connections among Graphs
     */
    public List<Subject> getPrerequisitesConnections() {
        return prerequisitesConnections;
    }

    public void setPrerequisitesConnections(List<Subject> prerequisitesConnections) {
        this.prerequisitesConnections = prerequisitesConnections;
    }

    /*
    It's the identifier of each subject. Generated by the code.
     */
    public int getSubjectCode() {
        return subjectCode;
    }

    public void setSubjectCode(int subjectCode) {
        this.subjectCode = subjectCode;
    }
}
